# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='Entry date')),
            ],
        ),
        migrations.AddField(
            model_name='letters',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morsecode.Message'),
        ),
    ]
