# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='letter',
            field=models.CharField(default='', editable=False, max_length=1),
        ),
    ]
