# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode', '0002_auto_20160704_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letters',
            old_name='letter',
            new_name='letter_text',
        ),
    ]
