# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode', '0003_auto_20160704_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='letter_text',
            field=models.CharField(max_length=1),
        ),
    ]
